### ISSUE TITLE
Write text for "Who we are"

### ISSUE THREAD

**Issue by eweilow** [aesirkth/website#1]
Current text is:
> ÆSIR consists of 33 students from KTH Royal Institute of Technology, in Stockholm. We are spread over several programmes and degrees - including Engineering Physics, Electrical Engineering and Aerospace Engineering. Our team is multicultural, with over 12 nations represented.

How it looks on the webpage:
![image](https://cloud.githubusercontent.com/assets/1054111/23227884/ca32b5e0-f93a-11e6-883e-424847397602.png)

**Comment by stovatt** [comment]
ÆSIR is an amateur rocket society based at Royal Institute of Technology in Stockholm. We were founded September 12th 2016. We consist of around 30 students spread over several programmes and degrees -- including Engineering Physics, Electrical Engineering and Aerospace Engineering. Our team is multicultural, with 15 different nations represented.
