### ISSUE TITLE
Write text for PR team

### ISSUE THREAD

**Issue by eweilow** [aesirkth/website#10]

**Comment by stovatt** [comment]
Suggestion: PR team takes care of our public relations. They work with graphic design, video, photography, and outreach in social media and on our website. They are also responsible for coordinating contact with potential sponsors and participation in fairs. Their goal is to make the association known to potential new members and to acquire resources to finance our projects.

**Comment by eweilow** [comment]
Slight edit:
>PR team take care of our public relations. They work with graphic design, video, photography, and outreach in social media as well as on our website. They are also responsible for coordinating contacts with sponsors and partners, as well as arranging our participation in fairs. Their goal is to make the association known to potential new members and to acquire the resources needed to complete our projects.

**Comment by stovatt** [comment]
That is better.

**Comment by eweilow** [comment]
Closing this for now.
