### ISSUE TITLE
Write text for events team

### ISSUE THREAD

**Issue by eweilow** [aesirkth/website#11]

**Comment by stovatt** [comment]
Suggestion: Events team arranges social activities like lectures, parties and BBQs. They are not very responsible at all. Their goal is to make sure all team members have fun while they learn together.

**Comment by eweilow** [comment]
Edited your version:
>Events team arrange internal social activities like parties and BBQs, but also outreach activities like lectures and meetups. Their work go hand in hand with the work of the PR team, but is more focused on the events where recruitment to ÆSIR happens and spreading the knowledge we gain. Their goal is to make the team members have fun while learning together.

What do you think?

**Comment by stovatt** [comment]
A lot better.
