### ISSUE TITLE
Get picture of propulsion team

### ISSUE THREAD

**Issue by eweilow** [aesirkth/website#14]
Should be of the team members (preferrably doing something team-related).

We sort of have a good picture already, maybe we can use that one?
![img_1559](https://cloud.githubusercontent.com/assets/1054111/23414387/012fcea2-fddc-11e6-85e9-e2a86e45de2f.JPG)

**Comment by stovatt** [comment]
It will work for now. If they do anything more team related later and take a picture of it we can change then.
