### ISSUE TITLE
Write text for "Our mission"

### ISSUE THREAD

**Issue by eweilow** [aesirkth/website#2]
Current text is:
> ÆSIR was created to provide a forum for students with an interest in rocket propulsion, where they can develop their passion. The activities of the association will further strengthen KTH position as a leading Aerospace University. 
Our mission is to become one of the top student organizations for rocket building in the world, by breaking and holding the student altitude records (which is currently 21.5 kilometers). Ultimately, we intend to break the worldwide altitude record and reach altitudes beyond the 120 kilometer mark.

How it looks on the webpage:
![image](https://cloud.githubusercontent.com/assets/1054111/23227918/ecbe7e14-f93a-11e6-9b76-1ca2cc56ec7e.png)

**Comment by stovatt** [comment]
ÆSIR was created to provide a forum for students with an interest in rocketry, where they can develop their passion. Our goal is to educate students in rocketry and engineering and give our members real world engineering experience. The activities of the association will further strengthen KTH position as a leading Aerospace University. 

Our mission is to become one of the top student organisations for rocket building in the world, by breaking and holding the student altitude records (which is currently above 30 kilometers). Ultimately, we intend to break the worldwide altitude record and reach altitudes beyond the 120 kilometer mark.
