### ISSUE TITLE
Write text for "Join us"

### ISSUE THREAD

**Issue by eweilow** [aesirkth/website#4]
The current text is:
>ÆSIR was created by students for students to learn. We are always looking into new talent and skills. If you are interested in joining us, let us know in the form below. We'll contact you in the future.

How it looks on the webpage:
![image](https://cloud.githubusercontent.com/assets/1054111/23227952/02c85e46-f93b-11e6-9857-325a9fbe12fd.png)

**Comment by stovatt** [comment]
I think the text is good. You could tell them to write which team(s) they are interested in joining as well.

**Comment by eweilow** [comment]
Added a "describe yourself" field, but I think we should leave the team selection for when we actually get back to them with a more detailed form. 👍
