### ISSUE TITLE
Get a new "Who we are"-picture

### ISSUE THREAD

**Issue by eweilow** [aesirkth/website#40]
The current one is sort of boring 
![image](https://aesir.se/4f6421974edab08367d581e9a99906f0.jpg)

**Comment by MatiasKidron** [comment]
We could take a new photo when ODIN is ready. AESIR people standing behind ODIN, which is laying horizontally on some desk for example.

**Comment by eweilow** [comment]
Outside! It has to be outside 🌳

**Comment by Monras** [comment]
![img_1528](https://user-images.githubusercontent.com/42514622/49883494-23ab0d80-fe33-11e8-8515-6e217b1edb10.jpg)
How about this one! :D

**Comment by MatiasKidron** [comment]
Yes this really good!
