### ISSUE TITLE
[Discussion] What are the goals with our website?

### ISSUE THREAD

**Issue by eweilow** [aesirkth/website#41]
Follow up from https://github.com/aesirkth/website/issues/38

### Why do we have the website?

I'm thinking these three distinct reasons:
- Recruiting students at KTH
- Getting sponsors
- Learning interested people about ÆSIR

Let's make this a long term discussion (and involve anyone who express thoughts about it!)
@stovatt 
@MatiasKidron

**Comment by MatiasKidron** [comment]
I also believe that these are the main functions of the site!

**Comment by stovatt** [comment]
I also agree. I think it is ok as it is now, as long as we keep it updated (not like the project descriptions right now). But long term I would like to have more detailed information about the association and our projects.
