### ISSUE TITLE
Update our sponsor list

### ISSUE THREAD

**Issue by eweilow** [aesirkth/website#43]
Is needed to do https://github.com/aesirkth/website/pull/42

Basically we need to update the content in https://github.com/aesirkth/website/tree/sponsors/src/routes/home/content/sponsors with our current sponsors.

**Comment by eweilow** [comment]
A preview of how sponsor lists look can be found at https://5a986d7f92226a68b9ca313d--aesir.netlify.com/

**Comment by stovatt** [comment]
We have gotten support from a lot of organisations, from quite a lot of money (like KTH OF and SNSB) to material support (TP filter, smaller things for electronics etc.) and the kind of money we get from UFS and Astronomisk ungdom. Who do we want to mention as a sponsor on the website? And what does current mean? (For example with the Odin sponsors that is a bit unclear.)
@MatiasKidron as external, do you have any opinions?

**Comment by stovatt** [comment]
I think I would say that KTH Space Center, SNSB and UFS are current sponsors. KTH OF would not be a current sponsor, because from their point of view the project that we applied for money for is finished and Astronomisk ungdom wouldn't either because we haven't applied for project money from them. Maybe I would also include TP-filter, because (I think at least) we got quite a lot more support from them than from the other material sponsors.

**Comment by MatiasKidron** [comment]
We should mentioned everybody who has provided either money, materials or services! We don't have to have "current sponsors", just sponsors. Those who have given more can be mentioned first!

**Comment by eweilow** [comment]
Need logos (optional) with transparent backgrounds and text describing each sponsor we'd like to put on the page if it's going to happen. 

I like the idea of listing everyone who have supported us, perhaps asking them first though?

**Comment by MatiasKidron** [comment]
We should ask companies but I don't think we have to ask organisations like UFS or SNSB.

**Comment by eweilow** [comment]
Wouldn't UFS and THS need to be listed as organisations that we are a part of, not a sponsor? 👍 So that section needs to be added as well to the site

**Comment by MatiasKidron** [comment]
Well yeah that too but for example UFS has also sponsored us.
