### ISSUE TITLE
Write texts for our current projects

### ISSUE THREAD

**Issue by eweilow** [aesirkth/website#5]
We need to decide what projects we want to list and what texts there should be in each project.

The project texts are hidden by default with only the title showing, but shows the texts when the items are clicked.

This is how it currently looks:
![image](https://cloud.githubusercontent.com/assets/1054111/23227998/378cab32-f93b-11e6-86c7-db0e1b2cee68.png)

**Comment by stovatt** [comment]
How long should the texts be?

**Comment by eweilow** [comment]
not longer than 
>Suspendisse semper augue velit, id consequat tortor fringilla nec. Praesent tincidunt dignissim augue quis tempus. Duis id tellus magna. Quisque eleifend sagittis sem ut ornare. Curabitur non diam tempus, finibus elit volutpat, gravida leo. Duis et malesuada lacus. Sed mollis rutrum mauris vel cursus. Mauris molestie, nunc condimentum aliquam suscipit, urna nunc viverra elit, sed semper leo sapien in massa. Praesent vel sem augue. Curabitur neque velit, sagittis non sodales vitae, tristique ut diam. Nullam non consequat turpis. Quisque pharetra felis vel turpis rutrum, eu hendrerit velit euismod. Ut mattis, augue vel bibendum cursus, quam nibh posuere augue, eu ultrices urna augue dapibus nunc. Cras eleifend enim quis quam fringilla venenatis sed a lacus.

**Comment by eweilow** [comment]
so not more than a 100 words

**Comment by stovatt** [comment]
Should I be able to see that text when I click on the pictures? Because I don't.

**Comment by eweilow** [comment]
that has not been added yet 😢
