### ISSUE TITLE
Update content post-Odin launch

### ISSUE THREAD

**Issue by eweilow** [aesirkth/website#59]
Continuing from #49 

Looking at the site - we should definitely create at least a new section called something along the lines of "What we've done".

- [ ] Create a new section for accomplished things
- [ ] Add Odin videos
- [ ] Add Odin pictures
- [ ] Change Odin text to reflect the accomplishments of the project
  - Lots of static fires
  - Successful launch
  - No recovery 😢 
- [ ] Change the punchline so that the video is clear?

**Comment by Monras** [comment]
![odin_info](https://user-images.githubusercontent.com/42514622/49883661-7dabd300-fe33-11e8-8cb9-ce86d5b9dbba.png)

**Comment by Monras** [comment]
And the short version video!
[ODIN Short Launch 2.zip](https://github.com/aesirkth/website/files/2672667/ODIN.Short.Launch.2.zip)

**Comment by Monras** [comment]
Best photos from the launch: 
[Best-20181212T164223Z-001.zip](https://github.com/aesirkth/website/files/2672700/Best-20181212T164223Z-001.zip)

**Comment by Monras** [comment]
![odin_withoutbackground](https://user-images.githubusercontent.com/42514622/49884922-51de1c80-fe36-11e8-882c-45555dd9ef83.png)

**Comment by eweilow** [comment]
Ideally the video should be hosted on a site that lets us embed a video player... So Vimeo, YouTube or I think Google Drive might work

**Comment by Monras** [comment]
https://www.youtube.com/watch?v=N74IE8Vk3NI 
We have it on our youtube channel! :D

**Comment by eweilow** [comment]
Excellent 👍
